
python_binary(name='hello-world-python-run',
  # Note: This uses `source` instead of `sources`, and only expects one file -- so you cannot use globs(".py") here
  # Though if you had a python_library that this depended on you can use `sources=globs("*.py")
  source="HelloWorld.py",
)
